#!/bin/bash.
cd ~/work
git clone https://github.com/walice/IllicitAIData.git
mv ~/work/IllicitAIData/Data.zip ~/work/Data.zip
rm ~/work/IllicitAIData -rf
unzip ~/work/Data.zip -d ~/work/
rm ~/requirements.R
mkdir ~/work/Results/